#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

# enable gnome keyring
eval $(/usr/bin/gnome-keyring-daemon --start --components=pkcs11,secrets,ssh)
export SSH_AUTH_SOCK

# picom
picom &

# polybar
${HOME}/.config/polybar/launch.sh --material

# set wallpaper
export CURRENT_BACKGROUND=$(find ~/Pictures/currentbg | shuf -n 1)
feh --bg-fill ${CURRENT_BACKGROUND} & 
${HOME}/.config/polybar/material/scripts/pywal.sh ${CURRENT_BACKGROUND} &

# start fusuma, restart if already started
kill $(ps aux | grep "[f]usuma" | awk '{print $2}') || true && fusuma -d -c ${HOME}/.config/fusuma/bspwm_config.yml

# notification center, restart if already started
kill $(pidof deadd-notification-center) || true && deadd-notification-center &

# redshift
[[ $(pidof redshift) == "" ]] && redshift &

# xfce4-power-manager
[[ $(pidof xfce4-power-manager) == "" ]] && xfce4-power-manager &

# clipmenu
export CM_LAUNCHER=rofi
clipmenud &

# Remove x cursor
xsetroot -cursor_name left_ptr

# set touchpad tap and two finger right-click
export TOUCHPAD_ID=$(xinput list --id-only 'PNP0C50:00 04F3:311D Touchpad')
export TAPPING_PROP_ID=$(xinput list-props $TOUCHPAD_ID | grep 'libinput Tapping Enabled (' | sed 's/[^0-9]\+//' | sed 's/):\s[0-9]//')
export CLICK_METHOD_ID=$(xinput list-props $TOUCHPAD_ID | grep 'libinput Click Method Enabled (' | sed 's/[^0-9]\+//' | sed 's/):\s[0-9],\s[0-9]//') 
xinput set-prop $TOUCHPAD_ID $TAPPING_PROP_ID 1 
xinput set-prop $TOUCHPAD_ID $CLICK_METHOD_ID 0 1

# disable screensaver
xset -dpms s off

# java applications
export _JAVA_AWT_WM_NONREPARENTING=1

bspc monitor -d I II III IV V VI VII VIII
# bspc monitor HDMI-1 -d IX X

bspc config border_width           1
bspc config window_gap             20
bspc config split_ratio            0.5
bspc config borderless_monocle     true
bspc config gapless_monocle        false
bspc config left_padding           30
bspc config right_padding          30
bspc config border_width           0
bspc config focus_follows_pointer  true

bspc rule -a AFNI state=floating
bspc rule -a TopLevelShell state=floating

