# The kitty terminal template for wallust
# Add to wallust config: kitty = { src='kitty.conf', dst='~/.config/kitty/colors.conf'}
# And add to kitty config: include colors.conf

cursor #A9A297

background #111018
foreground #FCFAD7

color0 #393940
color1 #2F0A0B
color2 #554A57
color3 #955444
color4 #E67640
color5 #FFB74D
color6 #F7F28D
color7 #F2F0BE
color8 #AAA885
color9 #2F0A0B
color10 #554A57
color11 #955444
color12 #E67640
color13 #FFB74D
color14 #F7F28D
color15 #F2F0BE

mark1_foreground #F7F171
mark2_foreground #F2EF98
mark3_foreground #F7F171
