# The kitty terminal template for wallust
# Add to wallust config: kitty = { src='kitty.conf', dst='~/.config/kitty/colors.conf'}
# And add to kitty config: include colors.conf

cursor #78A5C3

background #0C0E12
foreground #F0ECF4

color0 #37393E
color1 #765769
color2 #3A708E
color3 #C13B5C
color4 #9573A0
color5 #2988A2
color6 #A097A8
color7 #E2DCE7
color8 #9E9AA2
color9 #8A6078
color10 #3A82AB
color11 #EC2657
color12 #A66FB8
color13 #28ADD2
color14 #D5C9E0
color15 #E2DCE7

mark1_foreground #9279A8
mark2_foreground #CEB0E7
mark3_foreground #9279A8
