# The kitty terminal template for wallust
# Add to wallust config: kitty = { src='kitty.conf', dst='~/.config/kitty/colors.conf'}
# And add to kitty config: include colors.conf

cursor #ADCA9A

background #000207
foreground #F9F7FE

color0 #000208
color1 #507E96
color2 #5B843D
color3 #8C6B88
color4 #51B3B6
color5 #B0B532
color6 #B3ADBC
color7 #EFEBF5
color8 #A7A4AB
color9 #448AB1
color10 #619E36
color11 #B284AE
color12 #6CEFF3
color13 #EBF143
color14 #EFE7FB
color15 #EFEBF5

mark1_foreground #9E8ABC
mark2_foreground #D3BCF5
mark3_foreground #9E8ABC
