swipe:
  3:
    left:
      sendkey: 'LEFTALT+LEFT'
    right:
      sendkey: 'LEFTALT+RIGHT'
  4:
    left:
      sendkey: 'LEFTMETA+LEFTBRACE'
    right:
      sendkey: 'LEFTMETA+RIGHTBRACE'
    down:
      sendkey: 'LEFTALT+TAB'

